# Generated by Django 5.1.4 on 2025-04-13 13:41

import api.helpers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auction_end_time',
            field=models.DateTimeField(default=api.helpers.default_auction_end_time),
        ),
        migrations.AddField(
            model_name='item',
            name='highest_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_highest_bid', to='api.bid'),
        ),
    ]
