# Generated by Django 5.1.4 on 2025-05-09 15:11

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_auction_end_time_item_highest_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='auction_start_time',
            field=models.DateTimeField(default=api.helpers.default_auction_start_time),
        ),
    ]
