# Generated by Django 5.1.4 on 2025-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_auction_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('recent', 'recent'), ('past', 'Past')], default='upcoming', max_length=20),
        ),
    ]
