# Generated by Django 5.1.4 on 2025-06-04 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
